### ISSUE TITLE
Google Sheet Out of Date

### ISSUE THREAD

**Issue by Crosant** [Neraud/FFXIV_RetainerInventoryHelper#1]
Hello,

the Google Sheet you provide is out of date. Do you have a new one as a master copy?

Sincerly
Crosant

**Comment by Neraud** [comment]
I updated the csv files here, but I forgot to also update the reference spreadsheet.

I've generated a new reference spreadsheet, with updated data : https://docs.google.com/spreadsheets/d/1kiyA1TdEUvjWzhltMhDIJLUKEbQrOVIFx51Z88mHJBM

It's fixed in the README too (398d3ebe37a3debf4b6e1a7b83dfe660404b10a1)
